name: user
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  auto_size_text: ^3.0.0
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  conditional_builder_null_safety: ^0.0.6
  dartz: ^0.10.1
  dio: ^5.1.2
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_form_builder: ^9.1.1
  flutter_keyboard_visibility: ^5.4.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.2
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  go_router: ^11.1.2
  image_picker: ^0.8.4+11
  injectable: ^2.3.0
  internet_connection_checker: any
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  qr_flutter: ^4.1.0
  reactive_forms: ^16.1.0
  shared_preferences: null

dev_dependencies:
  build_runner: ^2.4.4

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Mont
      fonts:
        - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
